on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  #pull_request:
      #types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Coverage
      run: mvn sonar:sonar -Pcoverage
    - name: SonarCloud Scan
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=MelizsaGM_testingsq -Dsonar.organization=melizsagm -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GH_SQ }}
        SONAR_TOKEN: ${{ secrets.SQSECRET }}
